[package]
name = "connect4_nn_trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
rand = "0.8.5"
connect4_board_library = { git = "https://github.com/Dot32Dev/barebones_connectfour", rev = "546870e" }
